### ISSUE TITLE
Write blog post about g0v money distribution

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-blog#15]
they asked about it during a Hangout, it makes sense for me

**Comment by djahnie** [comment]
So this would be about time tracking and which tasks we see as relevant for receiving g0v money? Or is it just about the general percentages Stefan came up with?

**Comment by tiltec** [comment]
- explain where the money comes from and why we get it
- other usages of the money besides karrot (local foodsharing Taiwan work)
- we use time tracking, any (regular) contributor can add their active times
- link to spreadsheat
- maybe explain how to become a regular contributor (-> team member)

**Comment by tiltec** [comment]
Maybe I should write this now as a post-mortem to g0v..

**Comment by djahnie** [comment]
Could be useful. Now or never, I guess...

**Comment by tiltec** [comment]
I guess it's never then. We also never received any money, so I'll close this.
